
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OPEN_BR = 5;
  public static final int CLOSE_BR = 6;
  public static final int PREFIX = 11;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int IF = 8;
  public static final int ID = 13;
  public static final int ELSE = 9;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RPAREN = 4;
  public static final int EAR = 10;
  public static final int SUFFIX = 12;
  public static final int LPAREN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "OPEN_BR",
  "CLOSE_BR",
  "COMMA",
  "IF",
  "ELSE",
  "EAR",
  "PREFIX",
  "SUFFIX",
  "ID"
  };
}

